workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        XCODE_PROJECT: "iOSBuild/Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        BUNDLE_ID: "com.Stake.StapeDefenderGame"
        EXPORT_OPTIONS_PLIST: "exportOptions.plist"
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      node: 18.16.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Install CocoaPods
        script: |
          cd iOSBuild
          pod install
      - name: Build Unity project
        script: |
          /Applications/Unity/Hub/Editor/$(UNITY_VERSION)/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile \
            -projectPath . \
            -executeMethod BuildScript.BuildiOS \
            -quit
      - name: Build IPA
        script: |
          xcodebuild -workspace iOSBuild/Unity-iPhone.xcworkspace \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -archivePath build/ios/xcarchive/Unity-iPhone.xcarchive \
                     -allowProvisioningUpdates \
                     -destination 'generic/platform=iOS' \
                     archive

          xcodebuild -exportArchive \
                     -archivePath build/ios/xcarchive/Unity-iPhone.xcarchive \
                     -exportPath build/ios/ipa \
                     -exportOptionsPlist $EXPORT_OPTIONS_PLIST
    artifacts:
      - build/ios/ipa/*.ipa
